<a href="https://colab.research.google.com/github/ReemAlazmi28/python-data-science-portfolio/blob/main/02_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
### - scaler like 11
### - Arrys 1D (coloumn vector or row vector)
### - Matrix like 2D array
### - Tensor 3D array

N-dimensional array
as soon you define the size of the array we cant change it
 to use numpy we should call the library first

# 1D Array

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3]) #make an array then print it
a

array([1, 2, 3])

In [ ]:
type(a) #to print the type of the array

numpy.ndarray

In [ ]:
a.dtype # to print the data type of the array

dtype('int32')

In [ ]:
a.ndim # print the number of the dimention of the array

1

In [ ]:
a.shape # print the number of colunm and row of the array

(3,)

In [ ]:
a.size # the number of the elements in the array

3

In [ ]:
a.itemsize #the size of each element in byte

4

In [ ]:
a.data # the location of array in the memory

# 2D Array & 3D Array

In [ ]:
b = np.array( [
    [1,2,3],
    [3,4,5]
])
b

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
print('Type:',b.dtype)
print('number of diminions =' , b.ndim)
print('shape=', b.shape)
print('size =',b.size) #2*3

Type: int32
number of diminions = 2
shape= (2, 3)
size = 6


In [ ]:
# 3D Array
c = np.array ([
    [
        [1,2],
        [3,4]
    ],
    [
        [5,6],
        [7,8]
    ]

])


In [ ]:
print('Type:',c.dtype)
print('number of diminions =' , c.ndim)
print('shape=', c.shape)
print('size =',c.size)

Type: int32
number of diminions = 3
shape= (2, 2, 2)
size = 8


# Data Type

In [ ]:
x = np.array ([2.4,5.8])
x.dtype

dtype('float64')

In [ ]:
x = np.array([2.4,5.8], dtype=complex)
x.dtype

dtype('complex128')

In [ ]:
x = np.array(['Apple','ornage','banana'])
x.dtype #unicode sting

dtype('<U6')

In [ ]:
x = np.array([True,False,True])
x.dtype

dtype('bool')

In [ ]:
x = np.array(['orang',3.6,True])
x.dtype
# the system change the data type into one becase it does not eccept diff types in onle one type (Homogenuse)

dtype('<U32')

In [ ]:
x = np.array (['1','2'])
x.astype(int)

array([1, 2])

In [ ]:
#Tuple array
x = np.array((1,2,3))
x

array([1, 2, 3])

In [ ]:
x = np.array([(2,2),[2,3],(5,6)])
x

array([[2, 2],
       [2, 3],
       [5, 6]])

In [ ]:
np.zeros((2,3)) #2 rows , and 3 colomn of zeeos

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace and arange Function
## arrang start from the number that we incloud in the code but it does NOT end end with the last element is alaways end with the number befor the end
## linspace start from the num. that witen in the code also end with the num. that writen in the code

In [ ]:
np.arange(4,9) # 4=start point 9=end point (index 9)

array([4, 5, 6, 7, 8])

In [ ]:
np.arange(3,12,3) #3=start , 12=end , 3=gape (wich is the steps btweem each number)
#12 is not inclouded

array([3, 6, 9])

In [ ]:
np.arange(0,5,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
np.linspace(0,10,5)  #creat a matrix that start with 0 and end with10 the number  of elements are 5
#the gabe is selected outo from numpy library


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Random Function (Uniform Distribution)

In [ ]:
np.random.random((2,2))

array([[0.58277745, 0.77209422],
       [0.71954914, 0.05466461]])

In [ ]:
np.random.rand(3,2)

array([[0.37187329, 0.95741035],
       [0.50351432, 0.02467977],
       [0.38751556, 0.33854344]])

# Normal Distribution

In [ ]:
np.random.randn(2,1) #gave me a negative number

array([[-0.687835 ],
       [-0.2441382]])

In [ ]:
np.random.randint(3,15) #return a random number taht between the range 3-14

5

In [ ]:
np.random.randint(3,15,size=8 ) #return an arry with the size 8 (hase 8 randome numbers)

array([ 9, 11,  4,  7,  6,  6,  7,  4])

In [ ]:
np.random.randint(7, size=(2,3)) # 2d array with the size 2 by3 and that range from 0 to 6

array([[5, 4, 1],
       [1, 6, 5]])

# empty & full & eye

## full func.

In [ ]:
np.full((2,2),11) # crewat an array that it size =2 by 2 all it element are = 11

array([[11, 11],
       [11, 11]])

In [ ]:
np.full((2,2),[1,2]) # crewat an array that it size =2 by 2 all it element are the list 1 ,2

array([[1, 2],
       [1, 2]])

In [ ]:
np.full((4,4),[1,2,2,4])

array([[1, 2, 2, 4],
       [1, 2, 2, 4],
       [1, 2, 2, 4],
       [1, 2, 2, 4]])

## eye func.

In [ ]:
np.eye(5) # creates the indentity matrix with size 5 by 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## empty func.

In [ ]:
np.empty([3,2], dtype= int) #creat a merix size = 3 by 2 whithout initialize the values of elements

array([[-94381568,       380],
       [        0,         0],
       [   131074,     32760]])

# Shape Manipulation
### The number of elements must stay the same after reshaping

In [ ]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.shape = (3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a.ravel() # change the shape of 2d to 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
a.transpose() #change the rows to columns and the coloumns to rows

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

# Mathematical Operations on Arrays

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [ ]:
a+4 # add 4 to all the elemt of the array a

array([4, 5, 6, 7])

In [ ]:
a + b # add array a to array b (each element wil be added to the corresponding element

array([ 4,  6,  8, 10])

In [ ]:
np.add(a,b)

array([ 4,  6,  8, 10])

In [ ]:
a - b

array([-4, -4, -4, -4])

In [ ]:
np.subtract(a,b)

array([-4, -4, -4, -4])

In [ ]:
np.multiply(a,b)

array([ 0,  5, 12, 21])

In [ ]:
np.divide(a,b)

array([0.        , 0.2       , 0.33333333, 0.42857143])

In [ ]:
a / b

array([0.        , 0.2       , 0.33333333, 0.42857143])

# Matrix Product
### the rule is that the  number of column for first metrix should = to the number of the rpws for the second metrix

In [ ]:
a = np.array([[4,5,6],[8,9,7]])
a.shape

(2, 3)

In [ ]:
b = np.array([1,2,3])
b.shape

(3,)

In [ ]:
c = np.dot(a,b)
c.shape
c

array([[15., 15., 15.],
       [24., 24., 24.],
       [33., 33., 33.]])

##  a dot b are not the same as b dot a

In [ ]:
a = np.arange(4,13).reshape(3,3)
a

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a.dot(b)

array([[15., 15., 15.],
       [24., 24., 24.],
       [33., 33., 33.]])

In [ ]:
b.dot(a)

array([[21., 24., 27.],
       [21., 24., 27.],
       [21., 24., 27.]])

# Increment & Decrement

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
#increment by 1
a += 1
a

array([5, 6, 7, 8])

In [ ]:
# increment by 4
a = np.arange(4)
a += 4
a

array([4, 5, 6, 7])

In [ ]:
a = np.arange(4)
# decrement by 1
a -= 1
a

array([-1,  0,  1,  2])

In [ ]:
a = np.arange(4)
#decrement by 4
a -= 4
a

array([-4, -3, -2, -1])

In [ ]:
a = np.arange(4)
# double
a *= 2
a

array([0, 2, 4, 6])

# Universal Functions

In [ ]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [ ]:
# square root
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [ ]:
# log
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [ ]:
#sine function
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
# exponential func.
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# Aggregate Functions

In [ ]:
a = np.array([3.3,4.5,1.2,5.7,0.3])
a

array([3.3, 4.5, 1.2, 5.7, 0.3])

In [ ]:
a.sum()

15.0

In [ ]:
a.min()

0.3

In [ ]:
a.max()

5.7

In [ ]:
a.argmax() # the index of the largest number

3

In [ ]:
a.mean() #average

3.0

In [ ]:
a.std() #standard daviation

2.0079840636817816

# Indexing

In [ ]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[4] # the num in index 4

14

In [ ]:
a[-1] # the last number (invers the index) insted saying 0    1    2   3     4    5   we say    -6   -5   -4   -3   -2   -1
                                                    #   10   11   12   13   14   15             10   11   12   13   14    15

15

In [ ]:
a[[1,3,4]]

array([11, 13, 14])

In [ ]:
# 2 D array
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
A[1,2]

15

In [ ]:
A[0,2]

12

In [ ]:
A[0][2] # SAME RESULTES

12

# Slicing
## its like we are chooseing a group of element (subset) in the array by there indx
### ArrayName[start: end: steps]
### if we didnt choose a number it will be by the defult values  ArrayName[0: last elemnt: 1]

### 1D array

In [ ]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [ ]:
a[1:4]

array([11, 12, 13])

In [ ]:
a[1:4:3]

array([11])

In [ ]:
a[:5:2]

array([10, 12, 14])

In [ ]:
a[::2]

array([10, 12, 14])

In [ ]:
a[:5:]

array([10, 11, 12, 13, 14])

In [ ]:
a[:]

array([10, 11, 12, 13, 14, 15])

### 2D array

In [ ]:
A = np.arange(10,19).reshape((3,3))
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
A[0,:]

array([10, 11, 12])

In [ ]:
A[0:2,0:2]

array([[10, 11],
       [13, 14]])

In [ ]:
A[[0,2],0:2] #FIRST row and first row we use[] cuz. the are not beside each other

array([[10, 11],
       [16, 17]])

### Loop Iterating

In [ ]:
a = np.arange(10,18)
a

array([10, 11, 12, 13, 14, 15, 16, 17])

In [ ]:
for i in a :
    print (i)

10
11
12
13
14
15
16
17


In [ ]:
a = np.arange(10,18).reshape((2,4))
a

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
# in 2d array we need nested loop
for row in a: #  all rows
    for item in row:# each element in each row
         print (item)

10
11
12
13
14
15
16
17


In [ ]:
for item in a.flat: # this function well invert a 2d array to 1d array
    print(item)

10
11
12
13
14
15
16
17


In [ ]:
a = np.arange(10,18).reshape((2,4))
a
np.apply_along_axis(np.mean, axis=1 , arr=a) # to apply mean in all elemnet in the matrix axsi = 1 (row by row)

array([11.5, 15.5])

In [ ]:
np.apply_along_axis(np.mean, axis=0 , arr=a) # to apply mean(avrege) in all elemnet in the matrix axsi = 1 (colomn by colomn)

array([12., 13., 14., 15.])

In [ ]:
#creat a func that add 200 for x
def func1(x):
    return x+200

In [ ]:
np.apply_along_axis(func1, axis=0 , arr=a) # add 200 to each element in the matrix

array([[210, 211, 212, 213],
       [214, 215, 216, 217]])

### Conditions

In [ ]:
a = np.random.random((4,4))
a

array([[0.73767041, 0.37855543, 0.85132895, 0.30563629],
       [0.04033713, 0.96805232, 0.26819149, 0.77545068],
       [0.20451931, 0.45713   , 0.49738037, 0.28993466],
       [0.23385441, 0.93602034, 0.63835277, 0.50738293]])

In [ ]:
a < 0.2 #return a boolen array that do that condetion <0.2

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a[a<0.2] # return the value that do the condetion

array([0.04033713])

### Extra Examples

In [ ]:
z = np.array([
    [2, 1, 0],
    [5, 6, 7],
    [3, 8, 9]
])

In [ ]:
z[[0,1],[0,2]]

array([2, 7])

In [ ]:
z[::1]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

In [ ]:
z[0:3, 0:3]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

In [ ]:
z[:]

array([[2, 1, 0],
       [5, 6, 7],
       [3, 8, 9]])

## Join the arrays

In [ ]:
x = np.zeros((3,3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
y = np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.vstack((x,y)) #vertical stack : join the matrises in a vertical way

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.hstack((x,y)) #horizental stack : join the matrises in a horisental way

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
x= np.array([1,2,3])
y= np.array([5,6,7])
z= np.array([8,9,10])


In [ ]:
np.column_stack((x,y,z)) # join the matreses as column we mostlly use this func. in 1 d array to return a 2 d array

array([[ 1,  5,  8],
       [ 2,  6,  9],
       [ 3,  7, 10]])

In [ ]:
np.row_stack((x,y,z))  # join the matreses as row use this func. in 1 d array to return a 2 d array

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### Split The matrses into many

In [ ]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
[b,c]= np.hsplit(a,2) # split horizantly

In [ ]:
b # is the first two column

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [ ]:
c # last two column

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [ ]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
[b,c]= np.vsplit(a,2) # split them virtically
b # first two rows

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
[b,c]= np.vsplit(a,2)
c #last two rows

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# to split the arry un unequaly we will use the function split
[x,y,z] = np.split (a, [1,3] , axis=1)  # axis = 1(the split by column)
x

array([[ 0],
       [ 4],
       [ 8],
       [12]])

In [ ]:
y

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

In [ ]:
z

array([[ 3],
       [ 7],
       [11],
       [15]])

In [ ]:
[x,y,z] = np.split (a, [2,3] , axis=0)  # axis = 0 ( the split will be rows)
x # print x

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
y # print y

array([[ 8,  9, 10, 11]])

In [ ]:
z # print z

array([[12, 13, 14, 15]])

### Copies & Views

## View

In [ ]:
a = np.array([1,2,3,4])
b =a

In [ ]:
print (a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [ ]:
a[2]= 0
print (a)
print(b) # both chenged cuse the are views for each other

[1 2 0 4]
[1 2 0 4]


In [ ]:
c = a[0:2]
c

array([1, 2])

In [ ]:
print (a)
print(b)

[1 2 0 4]
[1 2 0 4]


In [ ]:
a [0]=0 # the are pointing to each other if one changes the other also change
print (a)
print(b)

[0 2 0 4]
[0 2 0 4]


## Copy

In [ ]:
a = np.array([1,2,3,4])
b = a.copy()
print (a)
print(b)

[1 2 3 4]
[1 2 3 4]


In [ ]:
a [0] =0 # only a will change but be will not cuz b is a copy from a not its view (a does not point to b)
print (a)
print(b)

[0 2 3 4]
[1 2 3 4]
